### ISSUE TITLE
错误反馈

### ISSUE THREAD

**Issue by dearmiku** [beeth0ven/RxSwift-Chinese-Documentation#14]
十分感谢您的分享~

您把  Completable 写成 Completeable了~ 
![screenshot](https://user-images.githubusercontent.com/26378870/34033324-bd3f03da-e1b4-11e7-85db-62e2f6d892ac.png)

**Comment by beeth0ven** [comment]
谢谢提醒。

我会在下次发版时，将它纠正过来。
