### ISSUE TITLE
好像没有介绍 throttle 这个操作符？

### ISSUE THREAD

**Issue by baagod** [beeth0ven/RxSwift-Chinese-Documentation#29]

**Comment by beeth0ven** [comment]
Throttle 和 Debounce  属于同类型的操作符，ReactiveX 官方文档里面用同一页介绍了他们: [Debounce](http://reactivex.io/documentation/operators/debounce.html)

例外，这两个操作符页容易让人感到困惑，在不同语言的 Rx 中他们的作用也有差别，参见： [the throttle info link is wrong?](https://github.com/ReactiveX/RxSwift/issues/1591#issuecomment-372227141)

本中文文档尽量与官方保持一致，所以没有加入 Throttle 操作符的介绍。
