### ISSUE TITLE
能否提供 PDF 格式下载

### ISSUE THREAD

**Issue by airingursb** [beeth0ven/RxSwift-Chinese-Documentation#32]
RT

**Comment by beeth0ven** [comment]
你好，感谢你的关注！

这里提供一个 [PDF 版本](https://github.com/beeth0ven/RxSwift-Chinese-Documentation/releases/download/1.2.0/RxSwift-Chinese-Documentation.pdf)。

为了获取最好的阅读体验，个人建议还是下载 [epub 版本](https://github.com/beeth0ven/RxSwift-Chinese-Documentation/releases/download/1.1.0/RxSwiftChineseDocumentation.epub)。  

因为它支持 gif 动图，而本文档用了许多动图来做演示，因此将来的发行版本也会以 epub 格式为主、

**Comment by airingursb** [comment]
好的 谢谢

**Comment by takeTrace** [comment]
> 你好，感谢你的关注！
> 
> 这里提供一个 [PDF 版本](https://github.com/beeth0ven/RxSwift-Chinese-Documentation/releases/download/1.2.0/RxSwift-Chinese-Documentation.pdf)。
> 
> 为了获取最好的阅读体验，个人建议还是下载 [epub 版本](https://github.com/beeth0ven/RxSwift-Chinese-Documentation/releases/download/1.1.0/RxSwiftChineseDocumentation.epub)。
> 
> 因为它支持 gif 动图，而本文档用了许多动图来做演示，因此将来的发行版本也会以 epub 格式为主、

好像 PDF 版本和 epub 版的更新不同步么? 能直接发布到 gitbook 上生成的 PDF 下载或者 epub 就好了
