### ISSUE TITLE
pdf 文档

### ISSUE THREAD

**Issue by takeTrace** [beeth0ven/RxSwift-Chinese-Documentation#37]
希望能在 gitbook 上发布出完整的 PDF 版本, 比较方便学习和笔记

**Comment by takeTrace** [comment]
看到之前 issue 的pdf 和 epub 都不是最新发布的 commit, 希望能更新这两个格式的资料, 万分感谢

**Comment by beeth0ven** [comment]
你好，感谢你的关注！

这里提供一个最新（19年5月21日 发布）的 [PDF 版本](https://github.com/beeth0ven/RxSwift-Chinese-Documentation/releases/download/2.0.0/RxSwiftChineseDocumentation.pdf)。

为了获取最好的阅读体验，个人建议还是下载 [epub 版本](https://github.com/beeth0ven/RxSwift-Chinese-Documentation/releases/download/2.0.0/RxSwiftChineseDocumentation.epub)。  

因为它支持 gif 动图，而本文档用了许多动图来做演示，因此将来的发行版本也会以 epub 格式为主、

**Comment by beijiahiddink** [comment]
> 你好，感谢你的关注！
> 
> 这里提供一个最新（19年5月21日 发布）的 [PDF 版本](https://github.com/beeth0ven/RxSwift-Chinese-Documentation/releases/download/2.0.0/RxSwiftChineseDocumentation.pdf)。
> 
> 为了获取最好的阅读体验，个人建议还是下载 [epub 版本](https://github.com/beeth0ven/RxSwift-Chinese-Documentation/releases/download/2.0.0/RxSwiftChineseDocumentation.epub)。
> 
> 因为它支持 gif 动图，而本文档用了许多动图来做演示，因此将来的发行版本也会以 epub 格式为主、

epub版本打不开啊提示是坏的   mac 10.15.1  Books 2.1

**Comment by beeth0ven** [comment]
@beijiahiddink 你好，

亲测 epub 版本，在 mac OS 10.14.4，Books 1.18 可以正常打开。

由于我身边没有 mac 10.15.1 Books 2.1 的机器，暂时无法验证图书兼容性。

你可以通过以下网盘重新下载图书，看能不能解决该问题：

   [下载地址](https://nextcloud.picroup.com:444/s/4jKStw2gL84Y8pH)
   密码：rxswift
