### ISSUE TITLE
怎么理解Observable的附加作用

### ISSUE THREAD

**Issue by kkkelicheng** [beeth0ven/RxSwift-Chinese-Documentation#46]
怎么理解Observable的附加作用就是subscribe函数？
虽然文档解释了是类似于Observeable.create({})。
然后文章直接给出了，这里的闭包` { (observer) -> Disposable in ... } `可以看作是 subscribe 函数。
。。。

小弟不才，还请大佬指导一下。
`public func subscribe<Observer>(_ observer: Observer) -> RxSwift.Disposable`
subscribe函数哪里来的附加作用。

**Comment by beeth0ven** [comment]
抱歉 @kkkelicheng ，让你久等了，由于我最近有点忙，还没来得及回复你。

你提的问题非常具有代表性，我需要整理一下思维。

在下周之前回答你提出的问题。

谢谢你的关注！

**Comment by beeth0ven** [comment]
> 怎么理解Observable的附加作用就是subscribe函数？
虽然文档解释了是类似于Observeable.create({})。
然后文章直接给出了，这里的闭包{ (observer) -> Disposable in ... }可以看作是 subscribe 函数。
。。。
>
>小弟不才，还请大佬指导一下。
`public func subscribe<Observer>(_ observer: Observer) -> RxSwift.Disposable`
subscribe函数哪里来的附加作用。

你好，`public func subscribe<Observer>(_ observer: Observer) -> RxSwift.Disposable` 是一个抽象的 interface.
而在具体的使用场景中, `func subscribe` 的内部实现是确定的，而这些内部实现往往会包含诸如：

* 网络请求
* 点击事件，用户输入
* 数据库操作
* ...

类似的的附加作用 。

如果你有任何疑问，还请给我留言。
谢谢！
