### ISSUE TITLE
对于已弃用的api Variable，文档中应该及时更新，不然容易误导 后来学习者

### ISSUE THREAD

**Issue by liuious** [beeth0ven/RxSwift-Chinese-Documentation#50]
<img width="1518" alt="image" src="https://user-images.githubusercontent.com/10148789/164873729-fd9de75b-82f1-4bc0-bb8e-e6e62ee73c59.png">

**Comment by beeth0ven** [comment]
谢谢你的提醒。
本文档给你带来的不便，我深表歉意。接下来我会评估更新文档所需的时间。看能不能将它同步到最新 （RxSwift 6.*）。
由于我有一段时间没有使用新版本的 RxSwift 6，所以我不能保证更新工作一定能顺利进行。我个人希望可以尽快将其完成。
谢谢！

**Comment by beeth0ven** [comment]
文档已更新到 RxSwift 6
境外可以访问：https://beeth0ven.github.io/RxSwift-Chinese-Documentation/
境内可以访问：https://rxswift.picroup.com/
谢谢！
