### ISSUE TITLE
epub的字体大小使用非标准版本?

### ISSUE THREAD

**Issue by RbBtSn0w** [beeth0ven/RxSwift-Chinese-Documentation#56]
![image](https://user-images.githubusercontent.com/1135031/167265128-4b3bc648-6a5b-404e-8c61-a6bb82c5093e.png)

对于RxSwift的提供书, 在设置好的iBook下, 所有书大小字体都是同等大小. 
而RxSwift的书籍的字体就非常大.

**Comment by beeth0ven** [comment]
谢谢你的关注！
对于这个问题，抱歉，目前没有找到完美的解决方案。
因为这个 epub 格式的书籍是使用默认配置导出来的，我也没有找到在哪里设置（导出书籍的）默认字体大小。
临时的解决方案就是在阅读本书时将字体手动调小，看完本书后再把字体还原：

![Screen Shot 2022-05-09 at 18 29 07](https://user-images.githubusercontent.com/5554127/167392566-0b2c9640-bb5e-4b3b-a496-96e1f19bcc4e.png)

希望以上建议能够帮到你。

**Comment by RbBtSn0w** [comment]
> 谢谢你的关注！ 对于这个问题，抱歉，目前没有找到完美的解决方案。 因为这个 epub 格式的书籍是使用默认配置导出来的，我也没有找到在哪里设置（导出书籍的）默认字体大小。 临时的解决方案就是在阅读本书时将字体手动调小，看完本书后再把字体还原：
> 
> ![Screen Shot 2022-05-09 at 18 29 07](https://user-images.githubusercontent.com/5554127/167392566-0b2c9640-bb5e-4b3b-a496-96e1f19bcc4e.png)
> 
> 希望以上建议能够帮到你。

关于“epub 格式的书籍是使用默认配置导出来的” 这个是通过什么平台导出的呢? 
如果可以, 我看能否抽个时间一起看看能否找到导出默认字体大小的解决办法.

**Comment by beeth0ven** [comment]
谢谢你的关注，

本书是使用 gitbook-cli 导出的，以下为简要步骤：
 1. 安装 [node js](https://nodejs.org/en/download/) ，建议版本为 [v12.16.3](https://nodejs.org/download/release/v12.16.3/)（我本地使用的这个版本）
 2. 安装 gitbook-cli 参考: https://github.com/GitbookIO/gitbook/blob/master/docs/setup.md
 3. 在本仓库根目录运行 `gitbook install` 安装依赖
 4. 切换到本仓库的 [epub](https://github.com/beeth0ven/RxSwift-Chinese-Documentation/tree/epub) 分支
 5. 导出 epub 书籍，参考：https://github.com/GitbookIO/gitbook/blob/master/docs/ebook.md
 
如果遇到问题，可以给我留言，谢谢你的协助。

**Comment by beeth0ven** [comment]
thanks for trying ❤️!
